version: "3.1"

services:
  api:
    container_name: api
    restart: always
    build: .
    env_file: 
      - .env
    ports: 
      - "3000:${PORT}"
    depends_on: 
      - db
    command: ["yarn", "dev"]
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=Todo
    ports:
      - 27017:27017